- name: Make accessible Grafana repo
  yum:
    name: rbru-grafana-release
    state: present
  when: ansible_pkg_mgr in ['yum', 'dnf']

- import_role:
    name: cloudalchemy.grafana
  vars:
    grafana_dashboards_dir: files/dashboards
    grafana_package: "grafana"
    grafana_security:
      admin_user: 'admin'
      admin_password: 'admin'
