- import_role:
    name: gantsign.maven

- name: Copy pre-built Maven configuration
  copy:
    src: settings.xml
    dest: /opt/maven/apache-maven-3.6.3/conf/
    mode: u=rw,g=rw,o=rw

- name: Copy pre-built Maven security settings
  copy:
    src: settings-security.xml
    dest: /opt/maven/
    mode: u=rw,g=rw,o=rw
