- hosts: prod
  gather_facts: yes
  become: yes
  # should not use proxy environment

  roles:
    - role: jdk
      tags: jdk

    - role: grafana
      tags: grafana
      grafana_port: 8081 #TODO
      grafana_datasources:
        - name: Prometheus
          type: prometheus
          url: "http://{{ inventory_hostname }}:9090"
          basicAuth: false
          access: proxy
          isDefault: true

    - role: curl
      tags: curl


- hosts: prod
  gather_facts: yes
  become: yes
  environment: "{{ env_proxy | default('') }}"

  roles:
    - role: maven
      tags: maven
      maven_version: '3.6.3'

    - role: cloudalchemy.prometheus
      tags: prometheus
      prometheus_scrape_configs:
        - job_name: 'host'
          static_configs:
            - targets: ['localhost:9100']
              labels:
                env: prod
        - job_name: 'app'
          metrics_path: '/dbo/actuator/prometheus'
          static_configs:
            - targets: ['localhost:8080']
              labels:
                env: prod

    - role: cloudalchemy.node-exporter
      tags: node_exporter
      node_exporter_version: '1.0.1'
      node_exporter_enabled_collectors:
        - processes
        - systemd
        - tcpstat
        - meminfo_numa
        - mountstats
        - logind
        - ksmd

    - role: jmeter
      tags: jmeter
      jmeter_version: '5.3'
