- hosts: prod
  gather_facts: yes
  become: yes
  environment: "{{ env_proxy }}"

  pre_tasks:
    - name: Update package manager cache
      tags: cache
      run_once: true
      yum:
        name: tar
        state: present
        update_cache: yes
      ignore_errors: yes


  roles:
    - role: gantsign.maven
      tags: maven
      maven_version: '3.6.3'

    - role: cloudalchemy.prometheus
      tags: prometheus
      prometheus_scrape_configs:
        - job_name: 'host'
          static_configs:
            - targets: ['localhost:9100']
              labels:
                env: prod
        - job_name: 'app'
          metrics_path: '/dbo/actuator/prometheus'
          static_configs:
            - targets: ['localhost:8080']
              labels:
                env: prod

    - role: cloudalchemy.node-exporter
      tags: node_exporter
      node_exporter_version: '1.0.1'
      node_exporter_enabled_collectors:
        - processes
        - systemd
        - tcpstat
        - meminfo_numa
        - mountstats
        - logind
        - ksmd

    - role: cloudalchemy.grafana
      tags: grafana
      grafana_package: rbru-grafana-release
      grafana_security:
        admin_user: 'admin'
        admin_password: 'admin'
      grafana_datasources:
        - name: Prometheus
          type: prometheus
          url: 'http://localhost:9090'
          basicAuth: false
          isDefault: true
      grafana_dashboards_dir: files/grafana_dashboards
#      grafana_dashboards: # if internet accessible
#        - dashboard_id: 1860 # https://grafana.com/api/dashboards/1860
#          revision_id: 20 # https://grafana.com/api/dashboards/1860/revisions
#          datasource: prometheus

    - role: lean_delivery.jmeter
      tags: jmeter
      jmeter_version: '5.3'


  tasks:
    - name: Install jdk
      tags: jdk
      package:
        state: present
        name: java-1.8.0-openjdk-devel

    - name: Copy pre-built Maven configuration
      tags: maven
      copy:
        src: files/maven/settings.xml
        dest: /opt/maven/apache-maven-3.6.3/conf/
        mode: u=rw,g=rw,o=rw

    - name: Install git
      tags: git
      package:
        state: present
        name: git

    - name: Install curl
      tags: curl
      package:
        state: present
        name: curl

  post_tasks:
    - name: Start JMeter remote agent
      tags: jmeter
      shell: "nohup jmeter-server -Dserver.rmi.ssl.disable=true -Djava.rmi.server.hostname={{ ansible_host }} -Dserver.rmi.localport=42129 > /dev/null 2>&1 &"
      args:
        chdir: "{{ lookup('env','JMETER_HOME') }}"
